apiVersion: v1
name: syntasa
version: 8.2.2
appVersion: "7.1"
description: Helm Chart for SYNTASA Customer Intelligence Platform for Google Marketplace
home: https://www.syntasa.com/
icon: https://www.syntasa.com/wp-content/uploads/2018/01/SYN_Logo_Green.png
sources:
  - https://github.com/syntasa-dev/syntasa-google-marketplace-sentiment-anlytics
maintainers:
  - name: Kaushik Vinjamuri
    email: kaushik.vinjamuri@syntasa.com
  - name: Pradeepraj Chandrasekaran
    email: pradeepraj.chandrasekaran@syntasa.com
  - name: Sarath Botlagunta
    email: sarath.botlagunta@syntasa.com
  - name: Philip Crilley
    email: philip.crilley@syntasa.com